import bpy, os

# FBX-v3 hero-body correction pass.
# Keep the validated FBX truck, wheel animation, DCS registration/tuning, LOD plumbing
# and exporter path untouched. This pass only replaces the crude rectangular camper
# shell generated by build_tpg_tacoma.py with a tapered, cab-height-matched shell.

REMOVE_PREFIXES = (
    "CAMPER_BODY",
    "CAMPER_ROOF",
    "CAMPER_SIDE_GLASS_",
    "CAMPER_REAR_GLASS",
)

for obj in list(bpy.data.objects):
    if obj.name.startswith(REMOVE_PREFIXES):
        bpy.data.objects.remove(obj, do_unlink=True)

destroyed = os.environ.get("TPG_TACOMA_DESTROYED", "0") == "1"
paint = bpy.data.materials.get("TPG_TACOMA_Burnt" if destroyed else "TPG_TACOMA_Quicksand_4T8")
glass = bpy.data.materials.get("TPG_TACOMA_TintedGlass")
if paint is None or glass is None:
    raise RuntimeError("Tacoma hero-body materials are missing")


def make_mesh(name, verts, faces, material, smooth=True, bevel=0.0):
    me = bpy.data.meshes.new(name + "_mesh")
    me.from_pydata(verts, [], faces)
    me.update()
    obj = bpy.data.objects.new(name, me)
    bpy.context.collection.objects.link(obj)
    me.materials.append(material)

    # Match the UV contract used by build_tpg_tacoma.py. ED's default material
    # exporter requires a UV layer for the base/AORMS texture blocks even when the
    # source textures are effectively flat-color swatches. Without this, pyedm
    # aborts with "There is no such uv=None" on the hero replacement meshes.
    uv = me.uv_layers.new(name="UVMap")
    for loop in me.loops:
        co = me.vertices[loop.vertex_index].co
        uv.data[loop.index].uv = ((co.x * 0.18 + co.y * 0.13) % 1.0,
                                  (co.z * 0.32 + co.y * 0.17) % 1.0)

    if smooth:
        for poly in me.polygons:
            poly.use_smooth = True
    if bevel > 0.0:
        mod = obj.modifiers.new("hero_edge_soften", "BEVEL")
        mod.width = bevel
        mod.segments = 3
        bpy.context.view_layer.objects.active = obj
        try:
            bpy.ops.object.modifier_apply(modifier=mod.name)
        except Exception:
            pass
    return obj


# Cross-section points run driver-to-passenger. Compared with the old rectangular
# box, the upper shell shoulders pull inward and the crown rounds over. Three
# longitudinal stations introduce a subtle fore/aft taper so the topper follows the
# Tacoma bed and visually meets the cab roof instead of reading as a cargo crate.
stations = [
    (-1.03, 0.98, 0.00),
    (-1.84, 1.00, 0.04),
    (-2.68, 0.985, 0.015),
]
profile = [
    (-0.870, 1.155),
    (-0.852, 1.505),
    (-0.785, 1.650),
    (-0.650, 1.735),
    ( 0.000, 1.785),
    ( 0.650, 1.735),
    ( 0.785, 1.650),
    ( 0.852, 1.505),
    ( 0.870, 1.155),
]
verts = []
for x, width_scale, crown_add in stations:
    for y, z in profile:
        extra = crown_add * max(0.0, 1.0 - abs(y) / 0.87)
        verts.append((x, y * width_scale, z + extra))

n = len(profile)
faces = []
for s in range(len(stations) - 1):
    a = s * n
    b = (s + 1) * n
    for i in range(n - 1):
        faces.append((a + i, a + i + 1, b + i + 1, b + i))
faces.append(tuple(range(n - 1, -1, -1)))
rear0 = (len(stations) - 1) * n
faces.append(tuple(rear0 + i for i in range(n)))
make_mesh("CAMPER_HERO_SHELL_V4", verts, faces, paint, smooth=True, bevel=0.022)

# Trapezoidal side glazing follows the shell shoulder and leaves proper painted
# pillars instead of floating as an oversized rectangular insert.
for side in (-1, 1):
    y = side * 0.846
    win = [
        (-2.48, y, 1.285),
        (-1.24, y, 1.285),
        (-1.31, y, 1.585),
        (-2.41, y, 1.610),
    ]
    face = [(0, 1, 2, 3)] if side > 0 else [(3, 2, 1, 0)]
    make_mesh(f"CAMPER_SIDE_GLASS_HERO_{side}", win, face, glass, smooth=False)

# Rear hatch glass is narrower at the top and leaves a visible painted perimeter.
rear_x = -2.686
rear = [
    (rear_x, -0.655, 1.285),
    (rear_x,  0.655, 1.285),
    (rear_x,  0.585, 1.615),
    (rear_x, -0.585, 1.615),
]
make_mesh("CAMPER_REAR_GLASS_HERO", rear, [(0, 1, 2, 3)], glass, smooth=False)

print("[TPG TACOMA HERO V4] Replaced rectangular camper with tapered cab-height-matched shell")
